# Generated by Django 4.2.5 on 2023-09-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0002_remove_device_assigned_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='checked_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
